baseURL: "https://mahasemesta.xyz"
title: Mahasemesta
paginate: 5
theme: hugo-PaperMod

DisqusShortname: "https-mahasemesta-xyz"
googleAnalytics: "G-YNRC5F8LG5"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: false
    minifyOutput: true

languages:
    en:
        languageName: "EN"
        weight: 1
        menu:
            main:
                - name: About
                  url: about/
                  weight: 1
                  pre: bookmark
                - name: Blog
                  url: blog/
                  weight: 2
                  pre: book
                - name: Contact
                  url: contact/
                  weight: 3
                  pre: phone

outputs:
    home:
        - HTML
        - RSS
        - JSON

permalinks:
    blog: "blog/:title"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Story of Semesta"
    author: Akasha
    # author: ["Me", "You"] # multiple authors

    homesubtitle: Welcome, we provide various kind of hypnotherapy services. Either relaxing meditation or trauma healing.

    gotop: chevron-up

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowToc: false
    comments: true
    images: ["ms.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "favicon/android-chrome-192x192.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    # logo
    label:
         text: ""
         icon: favicon/android-chrome-192x192.png
         iconHeight: 50

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    cover:
         hidden: false # hide everywhere but not in structured data
         hiddenInList: false # hide on list pages and home
         hiddenInSingle: false # hide on single page

    #fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "description", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
