baseURL: "https://mahasemesta.xyz"
title: Mahasemesta
paginate: 5
theme: hugo-PaperMod

DisqusShortname: "https-mahasemesta-xyz"
googleAnalytics: "G-YNRC5F8LG5"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: false
    minifyOutput: true

languages:
    en:
        languageName: "EN"
        weight: 1
        menu:
            main:
                - name: About
                  url: about/
                  weight: 1
                - name: Articles
                  url: articles/
                  weight: 2
                - name: Contact
                  url: contact/
                  weight: 3
                
                
outputs:
    home:
        - HTML
        - RSS
        - JSON

permalinks:
    posts: "/:title/"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Story of Semesta"
    author: Akasha
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowToc: false
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Mahasemesta"
        Content: >
            Welcome to demo of hugo's theme PaperMod. ☄️ **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX. ☁️ PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    # logo
    label:
         text: "Mahasemesta"
         icon: icon.png
         iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    cover:
         hidden: false # hide everywhere but not in structured data
         hiddenInList: false # hide on list pages and home
         hiddenInSingle: false # hide on single page

    #fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "description", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    
    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
